name: MPP-Bot Prod Deployment

on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to server
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/mpp/dev
            rm -R MPP-Bot-Template
            git clone -b main https://github.com/GagePielsticker/MPP-Bot-Template.git
            cd MPP-Bot-Template
            echo "MPP_TOKEN=${{ secrets.MPP_TOKEN }}" >> .env
            echo "ENVIRO=prod" >> .env
            npm install 
            pm2 delete prod > /dev/null
            pm2 start npm --name "prod" -- start > /dev/null